apiVersion: v1
kind: ServiceAccount
metadata:
  name: our-eks-sa-name
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::1234567890:role/app1_eks_role
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-name
spec:
  provider: aws
  parameters:
    objects: |
        - objectName: "app1-super-secret-json"
          objectType: "secretsmanager"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-fetcher
  labels:
    app: secret-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-fetcher
  template:
    metadata:
    
      name: secret-fetcher
      labels:
        app: secret-fetcher
    spec:
      serviceAccountName: our-eks-sa-name
      
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "secrets-provider-name"
      
      containers:
        - name: secret-fetcher
          image: kymiddallscripts/secrets-test:latest
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
